from pathlib import Path
p=Path('games/wip/index.html')
s=p.read_text()
marker='/* RANDOM PROBLEM PASS V1 */'
if marker in s:
    raise SystemExit(0)
old="""function shuffled(a){a=a.slice();for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}\nfunction buildDeck(){\n const tiers=[\n  [[23,14],[32,18],[41,26],[43,25]],\n  [[56,32],[67,24],[72,35],[84,16]],\n  [[39,47],[58,43],[64,37],[78,46]]\n ];\n let last=localStorage.getItem('gridBreakerLastOpeningV1')||'',deck=[],sig='',tries=0;\n do{deck=tiers.flatMap(t=>shuffled(t));sig=deck.slice(0,4).map(p=>p.join('x')).join('|');tries++}while(sig===last&&tries<20);\n localStorage.setItem('gridBreakerLastOpeningV1',sig);return deck;\n}\nfunction makeProblem(){\n const bossPool=[[585,93],[76,253],[418,67],[84,326],[739,42],[57,641],[864,35],[69,472]];\n S.boss=S.node%5===0;let p;\n if(S.boss){let bi=Math.floor(S.node/5)-1;p=bossPool[bi%bossPool.length]}\n else{if(!S.deck.length)S.deck=buildDeck();let normalIndex=S.node-Math.floor(S.node/5)-1,prevA=S.a,prevB=S.b;if(normalIndex<S.deck.length)p=S.deck[normalIndex];else{do{let lo=S.node<20?2:3;p=[lo*10+Math.ceil(Math.random()*9),(1+Math.floor(Math.random()*5))*10+Math.ceil(Math.random()*9)]}while((p[0]===prevA&&p[1]===prevB)||(p[0]===prevB&&p[1]===prevA))}}\n"""
new="""function shuffled(a){a=a.slice();for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}\nfunction randInt(a,b){return a+Math.floor(Math.random()*(b-a+1))}\nfunction problemKey(p){return p[0]+'x'+p[1]}\nfunction recentProblems(){try{return JSON.parse(localStorage.getItem('gridBreakerRecentProblemsV2')||'[]')}catch(_){return[]}}\nfunction rememberProblem(p){let r=recentProblems(),k=problemKey(p);r=r.filter(x=>x!==k);r.push(k);if(r.length>12)r=r.slice(-12);localStorage.setItem('gridBreakerRecentProblemsV2',JSON.stringify(r))}\nfunction randomNormalProblem(){let recent=recentProblems(),p,tries=0;do{let tier=S.node<6?0:S.node<16?1:2;if(tier===0){p=[randInt(21,49),randInt(12,29)]}else if(tier===1){p=[randInt(31,79),randInt(16,49)]}else{p=[randInt(41,99),randInt(21,69)]}if(Math.random()<.5)p=[p[1],p[0]];tries++}while(tries<80&&(recent.includes(problemKey(p))||recent.includes(p[1]+'x'+p[0])||p[0]===p[1]||p[0]%10===0||p[1]%10===0));rememberProblem(p);return p}\nfunction randomBossProblem(){let recent=recentProblems(),p,tries=0;do{let three=randInt(2,9)*100+randInt(1,9)*10+randInt(1,9),two=randInt(2,9)*10+randInt(1,9);p=Math.random()<.5?[three,two]:[two,three];tries++}while(tries<80&&(recent.includes(problemKey(p))||recent.includes(p[1]+'x'+p[0])));rememberProblem(p);return p}\nfunction makeProblem(){\n S.boss=S.node%5===0;let p=S.boss?randomBossProblem():randomNormalProblem();\n"""
if old not in s:
    raise SystemExit('randomization target block not found')
s=s.replace(old,new,1)
s=s.replace('</style>',marker+'\n</style>',1)
p.write_text(s)
