from pathlib import Path
p=Path('games/wip/index.html')
s=p.read_text()
marker='/* FINAL JUICE PASS V1 */'
if marker in s:
    raise SystemExit(0)

# 1) CSS motion/feedback polish
css_old=".flash{position:absolute;inset:0;pointer-events:none;background:#fff0}.flash.on{animation:flash .18s linear}@keyframes flash{50%{background:#fff3}}"
css_new=css_old+".modal.on .card{animation:modalPop .16s cubic-bezier(.2,.9,.25,1.25)}.choice:active{transform:translateY(2px) scale(.985);filter:brightness(1.18)}.term.done{animation:sealLock .28s ease-out}.ctrl.ready{animation:readyThrob 1.05s ease-in-out infinite}.juicePulse{animation:juicePulse .26s ease-out}@keyframes modalPop{0%{transform:scale(.94);opacity:.4}100%{transform:scale(1);opacity:1}}@keyframes sealLock{0%{transform:scale(.94);filter:brightness(1.8)}70%{transform:scale(1.025)}100%{transform:scale(1)}}@keyframes readyThrob{50%{filter:brightness(1.22);transform:translateY(-1px)}}@keyframes juicePulse{45%{transform:scale(1.18);filter:brightness(1.6)}100%{transform:scale(1)}}"
if css_old not in s: raise SystemExit('css target missing')
s=s.replace(css_old,css_new,1)

# 2) Juice helpers
particles_old="function particles(px,py,n=16,opt={}){let c=opt.color||'#ffd36e',size=opt.size||4,spread=opt.spread||160,life=opt.life||.6,grav=opt.gravity||0,shape=opt.shape||'square';for(let i=0;i<n;i++)S.particles.push({x:px,y:py,vx:(Math.random()-.5)*spread,vy:(Math.random()-.5)*spread,t:life,life,color:c,size:size+(Math.random()<.3?1:0),gravity:grav,shape})}"
particles_new=particles_old+"\nlet juiceFreeze=0,juiceRings=[],juiceFlash=0;\nfunction rumble(ms=18){try{if(navigator.vibrate)navigator.vibrate(ms)}catch(_){}}\nfunction ring(px,py,color='#ffd36e',max=72,life=.42,width=3){juiceRings.push({x:px,y:py,color,max,t:life,life,width})}\nfunction pulseEl(id){let e=document.getElementById(id);if(!e)return;e.classList.remove('juicePulse');void e.offsetWidth;e.classList.add('juicePulse')}\nfunction hitLayer(big=false){tone(big?82:170,big?.16:.07,big?.038:.018,'sawtooth');setTimeout(()=>tone(big?760:920,big?.11:.045,big?.025:.012,'square'),big?32:18)}\nfunction milestoneJuice(){if(S.streak===4||S.streak===8||S.streak===12){let label=S.streak===4?'CHAIN':S.streak===8?'SURGE':'OVERDRIVE';textBurst(label+'!',W*.5,H*.32,'#ffd36e');ring(W*.5,H*.47,'#ffd36e',88,.52,3);particles(W*.5,H*.47,18,{color:'#ffd36e',size:3,spread:190,life:.7});tone(520+S.streak*20,.1,.02,'triangle');pulseEl('streakT')}}"
if particles_old not in s: raise SystemExit('particles target missing')
s=s.replace(particles_old,particles_new,1)

# 3) Choice click/open feedback
show_old="function showChoices(title,sub,choices){let m=document.getElementById('modal'),bossFinish=title==='FINISH THE BOSS';document.getElementById('mt').textContent=title;document.getElementById('ms').textContent=sub;m.classList.toggle('bossfinish',bossFinish);let l=document.getElementById('ml');l.innerHTML='';choices.forEach(c=>{let b=document.createElement('button');b.className='choice';b.textContent=bossFinish?c.label:(c.desc+' = '+c.label);b.onclick=()=>{m.classList.remove('on','bossfinish');c.fn()};l.appendChild(b)});m.classList.add('on')}"
show_new="function showChoices(title,sub,choices){let m=document.getElementById('modal'),bossFinish=title==='FINISH THE BOSS';document.getElementById('mt').textContent=title;document.getElementById('ms').textContent=sub;m.classList.toggle('bossfinish',bossFinish);let l=document.getElementById('ml');l.innerHTML='';choices.forEach(c=>{let b=document.createElement('button');b.className='choice';b.textContent=bossFinish?c.label:(c.desc+' = '+c.label);b.onclick=()=>{tone(260,.025,.01,'square');m.classList.remove('on','bossfinish');c.fn()};l.appendChild(b)});tone(bossFinish?190:310,.045,.012,'triangle');m.classList.add('on')}"
if show_old not in s: raise SystemExit('showChoices target missing')
s=s.replace(show_old,show_new,1)

# 4) Correct/wrong hit stack and milestone celebrations
answer_old="function answerTerm(i,v,ans){if(v===ans){S.solved[i]=true;S.lastPart=i;S.streak++;let dmg=14+Math.min(18,S.streak*2);S.enemy=Math.max(1,S.enemy-dmg);tone(640,.08,.025,'triangle');spawnBeam(i,false);let g=gridGeom(),r=g.rects[i],sx=r.x+r.w/2,sy=r.y+r.h/2;particles(sx,sy,14,{color:['#73dcff','#ffd36e','#ff8fb3','#b29cff','#8ef0a7','#ffad66'][i%6],size:4,spread:140,life:.62});particles(W*.5,H*.48,12,{color:'#ffd36e',size:4,spread:170,life:.58});textBurst('+'+ans,sx,sy,'#eef8ff');S.shake=Math.max(S.shake,.28);flash();if(S.boss){let waveDone=bossWaveIndices().every(j=>S.solved[j]);if(waveDone&&!S.solved.every(Boolean)&&S.bossWave===0){S.bossWave=1;tone(430,.09,.02,'triangle');particles(W*.5,H*.56,22,{color:'#f1c46a',size:4,spread:170,life:.7});setHint('FIRST WARD BROKEN. WAVE 2/2: the remaining place-value row is exposed.')}else setHint('Correct. '+S.parts[i][0]+' × '+S.parts[i][1]+' = '+ans+'. '+(S.solved.every(Boolean)?'All six seals are broken. COMBINE for the finishing strike.':'Seal shattered. Keep attacking this wave.'))}else setHint('Correct. '+S.parts[i][0]+' × '+S.parts[i][1]+' = '+ans+'. '+(S.solved.every(Boolean)?'All sectors charged. COMBINE them.':'That sector hit the target. Keep the chain alive and charge another.'))}else{S.hp--;S.streak=0;tone(110,.12,.025,'sawtooth');terms[i].classList.add('wrong');particles(W*.5,H*.48,10,{color:'#ff7a84',size:3,spread:120,life:.5});textBurst('MISS',W*.5,H*.41,'#ff8fb3');S.shake=Math.max(S.shake,.18);setTimeout(()=>terms[i].classList.remove('wrong'),240);setHint('Not quite. Break it smaller if needed. Example: 40 × 20 = 4 × 2 × 100.');if(S.hp<=0){S.hp=2;setHint('Core rebooted. The grid stays intact, so you can keep learning this problem.')}}renderUI()}"
answer_new="function answerTerm(i,v,ans){if(v===ans){S.solved[i]=true;S.lastPart=i;S.streak++;pulseEl('streakT');milestoneJuice();let dmg=14+Math.min(18,S.streak*2);S.enemy=Math.max(1,S.enemy-dmg);tone(640,.08,.025,'triangle');hitLayer(false);juiceFreeze=3;rumble(16);spawnBeam(i,false);let g=gridGeom(),r=g.rects[i],sx=r.x+r.w/2,sy=r.y+r.h/2,col=['#73dcff','#ffd36e','#ff8fb3','#b29cff','#8ef0a7','#ffad66'][i%6];particles(sx,sy,18,{color:col,size:4,spread:170,life:.68});particles(sx,sy,8,{color:'#fff3d2',size:2,spread:220,life:.45,shape:'diamond'});particles(W*.5,H*.48,15,{color:'#ffd36e',size:4,spread:190,life:.62});ring(sx,sy,col,46,.34,2);ring(W*.5,H*.48,'#fff0b0',34,.28,2);textBurst('+'+ans,sx,sy,'#eef8ff');S.shake=Math.max(S.shake,.34);juiceFlash=Math.max(juiceFlash,.16);flash();if(S.solved.every(Boolean)){ring(W*.5,H*.47,'#ffd36e',105,.62,4);textBurst(S.boss?'EXECUTE!':'GRID CHARGED!',W*.5,H*.31,'#ffd36e');particles(W*.5,H*.46,S.boss?34:24,{color:'#ffd36e',size:4,spread:230,life:.82});tone(980,.11,.025,'triangle');pulseEl('combine')}if(S.boss){let waveDone=bossWaveIndices().every(j=>S.solved[j]);if(waveDone&&!S.solved.every(Boolean)&&S.bossWave===0){S.bossWave=1;tone(430,.09,.02,'triangle');setTimeout(()=>tone(690,.1,.018,'square'),45);juiceFreeze=5;rumble(34);juiceFlash=.28;ring(W*.5,H*.55,'#f1c46a',120,.68,4);textBurst('WARD BROKEN!',W*.5,H*.38,'#ffd36e');particles(W*.5,H*.56,38,{color:'#f1c46a',size:4,spread:230,life:.85});setHint('FIRST WARD BROKEN. WAVE 2/2: the remaining place-value row is exposed.')}else setHint('Correct. '+S.parts[i][0]+' × '+S.parts[i][1]+' = '+ans+'. '+(S.solved.every(Boolean)?'All six seals are broken. COMBINE for the finishing strike.':'Seal shattered. Keep attacking this wave.'))}else setHint('Correct. '+S.parts[i][0]+' × '+S.parts[i][1]+' = '+ans+'. '+(S.solved.every(Boolean)?'All sectors charged. COMBINE them.':'That sector hit the target. Keep the chain alive and charge another.'))}else{S.hp--;S.streak=0;tone(110,.12,.025,'sawtooth');setTimeout(()=>tone(72,.1,.02,'square'),18);juiceFreeze=2;rumble(24);juiceFlash=.24;pulseEl('hpT');terms[i].classList.add('wrong');particles(W*.5,H*.48,14,{color:'#ff7a84',size:3,spread:150,life:.55});ring(W*.5,H*.48,'#ff7a84',55,.36,3);textBurst('MISS',W*.5,H*.41,'#ff8fb3');S.shake=Math.max(S.shake,.28);setTimeout(()=>terms[i].classList.remove('wrong'),240);setHint('Not quite. Break it smaller if needed. Example: 40 × 20 = 4 × 2 × 100.');if(S.hp<=0){S.hp=2;setHint('Core rebooted. The grid stays intact, so you can keep learning this problem.')}}renderUI()}"
if answer_old not in s: raise SystemExit('answerTerm target missing')
s=s.replace(answer_old,answer_new,1)

# 5) Final combine becomes the biggest feedback stack
final_old="function answerTotal(v,ans,vals){if(v===ans){S.enemy=0;S.streak+=2;S.combineFlash=1.1;spawnBeam(0,true);spawnBeam(1,true);spawnBeam(2,true);spawnBeam(3,true);tone(130,.12,.03,'sawtooth');setTimeout(()=>tone(520,.18,.025,'triangle'),60);particles(W*.5,H*.42,S.boss?70:40,{color:'#ffd36e',size:S.boss?6:5,spread:S.boss?280:220,life:S.boss?1.15:.9});particles(W*.5,H*.42,S.boss?38:22,{color:'#73dcff',size:4,spread:S.boss?230:180,life:S.boss?1:.75});textBurst((S.boss?'BOSS BREAK '+ans:'TOTAL '+ans),W*.5,H*.36,'#ffd36e');S.shake=Math.max(S.shake,S.boss?.68:.42);flash();setHint(vals.join(' + ')+' = '+ans+'. The whole grid fires at once!');renderUI();setTimeout(()=>{S.node++;S.hp=Math.min(S.mhp,S.hp+1);makeProblem()},950)}else{S.hp--;S.streak=0;tone(95,.15,.03);particles(W*.5,H*.44,8,{color:'#ff7a84',size:3,spread:110,life:.45});setHint('Check the final addition: '+vals.join(' + ')+' . The decomposition is right, so only the recombination needs fixing.');if(S.hp<=0)S.hp=2;renderUI()}}"
final_new="function answerTotal(v,ans,vals){if(v===ans){S.enemy=0;S.streak+=2;S.combineFlash=1.1;juiceFreeze=S.boss?8:6;juiceFlash=S.boss?.75:.48;rumble(S.boss?70:42);pulseEl('streakT');spawnBeam(0,true);spawnBeam(1,true);spawnBeam(2,true);spawnBeam(3,true);tone(92,.17,.04,'sawtooth');setTimeout(()=>tone(260,.13,.025,'square'),34);setTimeout(()=>tone(720,.2,.03,'triangle'),82);particles(W*.5,H*.42,S.boss?88:54,{color:'#ffd36e',size:S.boss?6:5,spread:S.boss?320:250,life:S.boss?1.25:1});particles(W*.5,H*.42,S.boss?48:30,{color:'#73dcff',size:4,spread:S.boss?270:210,life:S.boss?1.05:.82});particles(W*.5,H*.42,S.boss?28:18,{color:'#fff5d5',size:2,spread:S.boss?360:280,life:.7,shape:'diamond'});ring(W*.5,H*.42,'#fff3bf',S.boss?165:125,S.boss?.9:.68,5);ring(W*.5,H*.42,'#73dcff',S.boss?125:90,S.boss?.7:.54,3);setTimeout(()=>{ring(W*.5,H*.42,'#ffd36e',S.boss?190:145,.72,4);particles(W*.5,H*.42,S.boss?42:24,{color:'#ffd36e',size:4,spread:260,life:.8})},150);textBurst((S.boss?'BOSS BREAK '+ans:'TOTAL '+ans),W*.5,H*.34,'#ffd36e');S.shake=Math.max(S.shake,S.boss?.86:.58);flash();setHint(vals.join(' + ')+' = '+ans+'. The whole grid fires at once!');renderUI();setTimeout(()=>{S.node++;S.hp=Math.min(S.mhp,S.hp+1);makeProblem()},S.boss?1450:1120)}else{S.hp--;S.streak=0;tone(95,.15,.03);setTimeout(()=>tone(66,.12,.018,'square'),20);juiceFreeze=2;juiceFlash=.2;rumble(24);particles(W*.5,H*.44,12,{color:'#ff7a84',size:3,spread:140,life:.5});ring(W*.5,H*.44,'#ff7a84',58,.38,3);setHint('Check the final addition: '+vals.join(' + ')+' . The decomposition is right, so only the recombination needs fixing.');if(S.hp<=0)S.hp=2;renderUI()}}"
if final_old not in s: raise SystemExit('answerTotal target missing')
s=s.replace(final_old,final_new,1)

# 6) Freeze-frame and expanding ring rendering
draw_start_old="x.clearRect(0,0,W,H);let t=performance.now()/1000,cx=W*.5,cy=H*(S.boss?.61:.47),g=gridGeom();"
draw_start_new="x.clearRect(0,0,W,H);let now=performance.now()/1000,t=juiceFreeze>0?animT:now;if(juiceFreeze>0)juiceFreeze--;else animT=now;let cx=W*.5,cy=H*(S.boss?.61:.47),g=gridGeom();"
if draw_start_old not in s: raise SystemExit('draw start target missing')
s=s.replace(draw_start_old,draw_start_new,1)

render_old="for(const q of S.particles){q.t-=1/60;q.x+=q.vx/60;q.y+=q.vy/60;q.vy+=(q.gravity||0)/60;x.globalAlpha=clamp(q.t/(q.life||1)*1.3,0,1);x.fillStyle=q.color||'#ffd36e';if(q.shape==='diamond'){let s=q.size||4;x.fillRect(Math.round(q.x),Math.round(q.y+s/2),s,2);x.fillRect(Math.round(q.x+s/2),Math.round(q.y),2,s+2)}else if(q.shape==='text'){x.font='900 10px monospace';x.textAlign='center';x.fillText(q.text,Math.round(q.x),Math.round(q.y))}else{x.fillRect(Math.round(q.x),Math.round(q.y),(q.size||4),(q.size||4));}}S.particles=S.particles.filter(q=>q.t>0);x.globalAlpha=1;x.restore();x.textAlign='left';requestAnimationFrame(draw)"
render_new="for(const r of juiceRings){r.t-=1/60;let q=1-r.t/r.life;x.globalAlpha=clamp(r.t/r.life,0,1);x.strokeStyle=r.color;x.lineWidth=r.width;x.beginPath();x.arc(r.x,r.y,6+r.max*q,0,Math.PI*2);x.stroke()}juiceRings=juiceRings.filter(r=>r.t>0);if(juiceFlash>0){juiceFlash=Math.max(0,juiceFlash-1/28);x.globalAlpha=juiceFlash*.34;x.fillStyle=juiceFlash>.45?'#fff2c0':'#ffffff';x.fillRect(0,0,W,H)}for(const q of S.particles){q.t-=1/60;q.x+=q.vx/60;q.y+=q.vy/60;q.vy+=(q.gravity||0)/60;x.globalAlpha=clamp(q.t/(q.life||1)*1.3,0,1);x.fillStyle=q.color||'#ffd36e';if(q.shape==='diamond'){let s=q.size||4;x.fillRect(Math.round(q.x),Math.round(q.y+s/2),s,2);x.fillRect(Math.round(q.x+s/2),Math.round(q.y),2,s+2)}else if(q.shape==='text'){x.font='900 10px monospace';x.textAlign='center';x.fillText(q.text,Math.round(q.x),Math.round(q.y))}else{x.fillRect(Math.round(q.x),Math.round(q.y),(q.size||4),(q.size||4));}}S.particles=S.particles.filter(q=>q.t>0);x.globalAlpha=1;x.restore();x.textAlign='left';requestAnimationFrame(draw)"
if render_old not in s: raise SystemExit('particle renderer target missing')
s=s.replace(render_old,render_new,1)

s=s.replace('</style>',marker+'\n</style>',1)
p.write_text(s)
