from pathlib import Path
p=Path('games/wip/index.html')
s=p.read_text()
repls=[
("#bossTag{display:none;position:absolute;z-index:3;left:50%;top:36px;transform:translateX(-50%);padding:4px 8px;background:#2a160f;border:2px solid #aa8241;color:#ffd98b;font-size:8px;font-weight:1000;letter-spacing:.1em;white-space:nowrap;box-shadow:inset 0 0 0 2px #130c09,0 2px 0 #080504}#app.boss #bossTag{display:block}#app.boss #board{display:none}#app.boss #stage{margin-bottom:8px}#app.boss #split{font-size:8px}#app.boss #problem{top:9px;color:#ffe7ad}","#bossTag{display:none;position:absolute;z-index:3;left:50%;top:36px;transform:translateX(-50%);padding:3px 7px;background:#2a160f;border:2px solid #aa8241;color:#ffd98b;font-size:8px;font-weight:1000;letter-spacing:.1em;white-space:nowrap;box-shadow:inset 0 0 0 2px #130c09,0 2px 0 #080504}#app.boss #bossTag{display:block}#app.boss #board{display:none}#app.boss #stage{margin-bottom:6px}#app.boss #split{font-size:8px}#app.boss #problem{top:9px;color:#ffe7ad}"),
("setHint(S.boss?'A new place value has opened six seals. Tap a chamber in the grid to attack it.':'Each rectangle is a partial product. Charge all four, then combine them.');","setHint(S.boss?'Six readable boss chambers represent the place-value parts. Tap a chamber to attack its seal.':'Each rectangle is a partial product. Charge all four, then combine them.');"),
("function gridGeom(){let A=splitPlaces(S.a),B=splitPlaces(S.b),gw=Math.min(W*(S.boss?.84:.7),S.boss?310:250),gh=Math.min(H*(S.boss?.34:.27),S.boss?190:135),gx=(W-gw)/2,gy=H*(S.boss?.17:.12),xs=[gx],ys=[gy],acc=0;for(const a of A){acc+=a;xs.push(gx+gw*(acc/S.a))}acc=0;for(const b of B){acc+=b;ys.push(gy+gh*(acc/S.b))}let rects=[];for(let row=0;row<B.length;row++)for(let col=0;col<A.length;col++)rects.push({x:xs[col],y:ys[row],w:xs[col+1]-xs[col],h:ys[row+1]-ys[row],row,col});return {A,B,gw,gh,gx,gy,xs,ys,rects}}","function gridGeom(){\n let A=splitPlaces(S.a),B=splitPlaces(S.b),gw=Math.min(W*(S.boss?.82:.7),S.boss?304:250),gh=Math.min(H*(S.boss?.255:.27),S.boss?154:135),gx=(W-gw)/2,gy=H*(S.boss?.145:.12),xs=[gx],ys=[gy];\n const weights=arr=>arr.map(v=>S.boss?Math.max(1,String(Math.round(v)).length):v), edge=(vals,start,size)=>{let out=[start],sum=vals.reduce((a,b)=>a+b,0),acc=0;for(const v of vals){acc+=v;out.push(start+size*(acc/sum))}return out};\n if(S.boss){xs=edge(weights(A),gx,gw);ys=edge(weights(B),gy,gh)}else{xs=edge(A,gx,gw);ys=edge(B,gy,gh)}\n let rects=[];for(let row=0;row<B.length;row++)for(let col=0;col<A.length;col++)rects.push({x:xs[col],y:ys[row],w:xs[col+1]-xs[col],h:ys[row+1]-ys[row],row,col});return {A,B,gw,gh,gx,gy,xs,ys,rects}\n}"),
("x.fillText(S.boss?'ARCHON OF HUNDREDS':ENEMY_NAMES[kind],cx,cy-(S.boss?61:49));","x.fillText(S.boss?'ARCHON OF HUNDREDS':ENEMY_NAMES[kind],cx,cy-(S.boss?67:49));"),
("x.fillText(S.a+'×'+S.b,cx,cy+(S.boss?62:50));","x.fillText(S.a+'×'+S.b,cx,cy+(S.boss?66:50));"),
("x.clearRect(0,0,W,H);let t=performance.now()/1000,cx=W*.5,cy=H*.47,g=gridGeom();","x.clearRect(0,0,W,H);let t=performance.now()/1000,cx=W*.5,cy=H*(S.boss?.61:.47),g=gridGeom();"),
("if(S.streak>=4){let lvl=Math.min(4,Math.floor(S.streak/4)),count=4+lvl*2;for(let i=0;i<count;i++){let a=t*(1+lvl*.15)+i*Math.PI*2/count,r=58+lvl*9+(i%2)*7;x.fillStyle=lvl>=3?'#ffd36e':'#73dcff';let sz=lvl>=3?5:4;x.fillRect(Math.round(cx+Math.cos(a)*r-sz/2),Math.round(cy+Math.sin(a)*r-sz/2),sz,sz)}let label=S.streak>=12?'OVERDRIVE':S.streak>=8?'SURGE':'CHAIN';x.fillStyle=S.streak>=12?'#ffd36e':'#73dcff';x.font='900 10px monospace';x.textAlign='center';x.fillText(label+' x'+S.streak,cx,cy-70)}","if(S.streak>=4){let lvl=Math.min(4,Math.floor(S.streak/4)),count=S.boss?4:4+lvl*2;for(let i=0;i<count;i++){let a=t*(1+lvl*.15)+i*Math.PI*2/count,r=(S.boss?50:58)+lvl*(S.boss?4:9)+(i%2)*5;x.fillStyle=lvl>=3?'#ffd36e':'#73dcff';let sz=lvl>=3?5:4;x.fillRect(Math.round(cx+Math.cos(a)*r-sz/2),Math.round(cy+Math.sin(a)*r-sz/2),sz,sz)}if(!S.boss){let label=S.streak>=12?'OVERDRIVE':S.streak>=8?'SURGE':'CHAIN';x.fillStyle=S.streak>=12?'#ffd36e':'#73dcff';x.font='900 10px monospace';x.textAlign='center';x.fillText(label+' x'+S.streak,cx,cy-70)}}"),
("Each glowing rectangle is one partial product.","Each glowing chamber is one partial product.")
]
for old,new in repls:
    if old not in s: raise SystemExit('missing patch target: '+old[:80])
    s=s.replace(old,new,1)
p.write_text(s)
